version: "3"

services:
  template-backend:
    image: template-backend:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NODE_ENV: production
        PORT: ${APP_PORT}
    container_name: template-backend
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
